---
# This is an example playbook to execute Ansible tests.

- name: Verify CUDA toolkit installation
  hosts: all
  tasks:
  - name: Check that CUDA has been installed
    stat:
      path: /usr/local/cuda-11.2
    register: cuda_path_check
  - name: Verify that CUDA folder exists
    assert:
      that: cuda_path_check.stat.exists
- name: Verify NVIDIA driver kernel modules
  hosts: centos7_cuda_run
  tasks:
  - name: Check that NVIDIA kernel module has been installed
    find:
      path: /lib/modules/{{ cuda_driver_kernel_version }}
      patterns: nvidia.ko
    register: nvidia_module_find
  - name: Verify that kernel module exists
    assert:
      that: nvidia_module_find.matched > 0
